version: "3"

services:

  # kafkamysql:
  #   build: 
  #     context: .
  #     dockerfile: dev.Dockerfile
  #     args:
  #       - KAFKA_BROKER_URL=broker:9092

  generator:
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092

networks:
  default:
    external:
      name: kafka-network      